debug = true
port = "3000"
address = "0.0.0.0"
root_dir = "/home/betta/license_generator/templates"

[[server]]
  [server.location]
    path = "/api/v1"
    proxy_pass = "127.0.0.1:8000"

[[server]]
  [server.location]
    path = "/"
    static_path = "/"
