debug = false
port = "3000"
address = "0.0.0.0"
root_dir = "/home/betta/"

[[server]]
  [server.location]
    pattern = "/api/v1"
    proxy_pass = "127.0.0.1:8000"

[[server]]
  [server.location]
    pattern = "/"
    static_path = "/"
